## Ejercicio 1

Dada una matriz en formato numpy array, donde cada fila de la matriz representa un vector matemático.
Calular l0, l1, l2

In [2]:
import numpy as np
vector = np.array([[1, 1, 1], [2, 3, 4], [5, 6, 7]])
print("Array")
print(vector)

print("l0:")
print(np.linalg.norm(vector, ord=0, axis=1))
print(np.count_nonzero(vector, axis=1))
print(np.sum(vector != 0, axis=1))

print("\nl1:")
print(np.linalg.norm(vector, axis=1))
print(np.sum(np.power(vector, 2), axis=1) ** 0.5)

print("\nl2:")
print(np.linalg.norm(vector, ord=float("inf"), axis=1))
print(np.max(np.abs(vector), axis=1))


Array
[[1 1 1]
 [2 3 4]
 [5 6 7]]
l0:
[3. 3. 3.]
[3 3 3]
[3 3 3]

l1:
[ 1.73205081  5.38516481 10.48808848]
[ 1.73205081  5.38516481 10.48808848]

l2:
[1. 4. 7.]
[1 4 7]


## Ejercicio 2

Dada una matriz en formato numpy array, donde cada fila de la matriz representa un vector matemático, se requiere computar la norma l2 de cada vector. Una vez obtenida la norma, se debe ordenar las mísmas de mayor a menor. Finalmente, obtener la matriz original ordenada por fila según la norma l2.

In [65]:
vector = np.array([[1,2,3,4], [1,1,1,1], [0,0,0,1]])
print("Vector:")
print(vector)

norm = np.linalg.norm(vector, axis=1)
print("Norma del vector")
print(norm)

print("Orden de la norma")
argorder = np.argsort(norm, axis=-1)
print(argorder)

print("Vector ordenado segun la norma")
vector[argorder]
print(vector[argorder])


Vector:
[[1 2 3 4]
 [1 1 1 1]
 [0 0 0 1]]
Norma del vector
[5.47722558 2.         1.        ]
Oreden de la norma
[2 1 0]
Vector ordenado segun la norma
[[0 0 0 1]
 [1 1 1 1]
 [1 2 3 4]]


## Ejercicio 3

El objetivo es construir un índice para identificadores de usuarios, es decir id2idx e idx2id. Para ello crear una clase, donde el índice se genere en el constructor. Armar métodos get_users_id y get_users_idx

In [4]:
class Indexing:
    def __init__(self):
        self.users_id = np.array([15, 12, 14, 10, 1, 2, 1])
        self.users_idx = np.array([0, 1, 2, 3, 4, 5, 4])

    def get_users_id(self, idx):
        index = np.where(self.users_idx == idx)
        return self.users_id[index][0]

    def get_users_idx(self, id):
        index = np.where(self.users_id == id)
        return self.users_idx[index][0]

indexing = Indexing()
print("Get users idx of 1:")
value = indexing.get_users_idx(1)
print(value)

print("Get users id of 1:")
value = indexing.get_users_id(1)
print(value)


Get users idx of 1:
4
Get users id of 1:
12


Una solución equivalente podría ser:

In [3]:
class Indexing:
    def __init__(self):
        self.users_id = np.unique([15, 12, 14, 10, 1, 2, 1])
        print(self.users_id)
        self.users_idx = np.ones(np.max(self.users_id) + 1, dtype=int) * -1
        self.users_idx[self.users_id] = np.arange(self.users_id.shape[0])
        print(self.users_idx)

    def get_users_id(self, idx):
        return self.users_id[idx]

    def get_users_idx(self, id):
        return self.users_idx[id]

indexing = Indexing()
print("Get users idx of 1:")
value = indexing.get_users_idx(1)
print(value)

print("Get users id of 1:")
value = indexing.get_users_id(1)
print(value)


[ 1  2 10 12 14 15]
[-1  0  1 -1 -1 -1 -1 -1 -1 -1  2 -1  3 -1  4  5]
Get users idx of 1:
0
Get users id of 1:
2


## Ejercicio 4

En los problemas de clasificación, se cuenta con dos arreglos, la verdad (ground truth) y la predicción (prediction). Cada elemento de los arreglos puede tomar dos valores: True (representado por 1) y False (representado por 0). Por lo tanto, se pueden definir cuatro variables:

True Positive (TP): la verdad es 1 y la predicción es 1.

True Negative (TN): la verdad es 0 y la predicción es 0.

False Negative (FN): la verdad es 1 y la predicción es 0.

False Positive (FP): la verdad es 0 y la predicción es 1.

A partir de esas cuatro variables, se definen las siguientes métricas:

Precision = TP / (TP + FP)

Recall = TP / (TP + FN)

Accuracy = (TP + TN) / (TP + TN + FP + FN)

Para los siguientes arreglos, representando la verdad y la predicción, calcular las métricas anteriores con operaciones vectorizadas en NumPy.

truth = [1,1,0,1,1,1,0,0,0,1]
prediction = [1,1,1,1,0,0,1,1,0,0]

In [120]:
truth = np.array([1, 1, 0, 1, 1, 1, 0, 0, 0, 1])
prediction = np.array([1, 1, 1, 1, 0, 0, 1, 1, 0, 0])

TP = np.sum(truth * prediction)
print("TP: ", TP)
FP = np.sum(truth < prediction)
print("FP: ", FP)
TN = np.sum(truth == prediction) - TP
print("TN: ", TN)
FN = np.sum(truth > prediction)
print("FN: ", FN)

precision = TP / (TP + FP)
print("Precision: ", precision)
recall = TP / (TP + FN)
print("Recall: ", recall)
accuracy = (TP + TN) / (TP + TN + FP + FN)
print("Accuracy: ", accuracy)



TP:  3
FP:  3
TN:  1
FN:  3
Precision:  0.5
Recall:  0.5
Accuracy:  0.4


## Ejercicio 5

En information retrieval o search engines, en general contamos con queries “q” y para cada “q” una lista de documentos que son verdaderamente relevantes. Para evaluar un search engine, es común utilizar la métrica average query precision. Tomando de referencia el siguiente ejemplo, calcular la métrica con NumPy utilizando operaciones vectorizadas.

In [37]:
T = True
F = False
q_id = np.array([1, 1, 1, 1, 2, 2, 2, 3, 3, 3, 3, 3, 4, 4, 4, 4])
predicted_rank = np.array([0, 1, 2, 3, 0, 1, 2, 0, 1, 2, 3, 4, 0, 1, 2, 3])
truth_relevance = np.array([T, F, T, F, T, T, T, F, F, F, F, F, T, F, F, T])

# Get bincount of every id
counts = np.bincount(q_id)
# Replace values that are zero to be able to divide
counts = np.where(counts==0, -1, counts)
# Get true values number for every query id
truth_counts = np.bincount(q_id * truth_relevance)
# Get proportion of truth values
true_proportion = truth_counts / counts
# Filter negative values
true_proportion = np.where(true_proportion<0, 0, true_proportion)
# Get average precision
avg_precision = np.sum(true_proportion) /  np.unique(q_id).shape[0]
print("The average precision is: {}".format(avg_precision))


The average precision is: 0.5


## Ejercicio 6

Dada una nube de puntos X y centroides C, obtener la distancia entre cada vector X y los centroides utilizando operaciones vectorizadas y broadcasting en NumPy. Utilizar como referencia los siguientes valores:

In [5]:
X = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
C = np.array([[1, 0, 0], [0, 1, 1]])   

print("X: ")
print(X)
print("\nC: ")
print(C)
print("\nX - C[:, None]: ")
print(X - C[:, None])
print("\nDistance:")
print(np.linalg.norm(X - C[:, None], axis=2))

distance = np.linalg.norm(X - C[:, None], axis=2)


X: 
[[1 2 3]
 [4 5 6]
 [7 8 9]]

C: 
[[1 0 0]
 [0 1 1]]

X - C[:, None]: 
[[[0 2 3]
  [3 5 6]
  [6 8 9]]

 [[1 1 2]
  [4 4 5]
  [7 7 8]]]

Distance:
[[ 3.60555128  8.36660027 13.45362405]
 [ 2.44948974  7.54983444 12.72792206]]


## Ejercicio 7

Obtener para cada fila en X, el índice de la fila en C con distancia euclídea más pequeña. Es decir, para cada fila en X, determinar a qué cluster pertenece en C. Hint: usar np.argmin.

In [39]:
print("Los indices para cada fila son: {}".format(np.argmin(distance, axis=0)))

Los indices para cada fila son: [1 1 1]
